# Clone Repo

In [ ]:
# Clone cleaned up repo
!git clone https://github.com/javaliKai/warehouse-activity-tracker.git

fatal: destination path 'warehouse-activity-tracker' already exists and is not an empty directory.


# Install Deps

In [ ]:
# verify pytorch installation
import torch
print("Torch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA version:", torch.version.cuda)

Torch: 2.10.0+cu128
CUDA available: True
CUDA version: 12.8


In [ ]:
# set cuda home
import os
os.environ["CUDA_HOME"] = "/usr/local/cuda"  # this is the default google colab location of cuda
print(os.environ["CUDA_HOME"])

/usr/local/cuda


In [ ]:
# install SAM2
!cd warehouse-activity-tracker && pip install -e .

Obtaining file:///content/warehouse-activity-tracker
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  Building editable for SAM-2 (pyproject.toml) ... done
  Created wheel for SAM-2: filename=sam_2-1.0-0.editable-cp312-cp312-linux_x86_64.whl size=24134 sha256=8647fa32f555931c5cbd3a72598075b2ee42978d938e14954ccea177ad42d7e4
  Stored in directory: /tmp/pip-ephem-wheel-cache-dmfvhdox/wheels/2f/6a/01/1151ac797fd33b5746405ed3fb3e55062c7f5abaa4f0a021a4
Successfully built SAM-2
  Attempting uninstall: SAM-2
    Found existing installation: SAM-2 1.0
    Uninstalling SAM-2-1.0:
      Successfully uninstalled SAM-2-1.0


In [ ]:
# install grounding dino
!cd warehouse-activity-tracker/ && pip install --no-build-isolation -e grounding_dino

Obtaining file:///content/warehouse-activity-tracker/grounding_dino
  Preparing metadata (setup.py) ... done
  Attempting uninstall: groundingdino
    Found existing installation: groundingdino 0.1.0
    Uninstalling groundingdino-0.1.0:
      Successfully uninstalled groundingdino-0.1.0
  Running setup.py develop for groundingdino


In [ ]:
# install extra deps that are not listed in the setup.py
!pip install supervision addict yapf

# Download Checkpoints

In [ ]:
# For SAM2 checkpoints -- currently using custom to directly get base ckpt
%cd /content/warehouse-activity-tracker/checkpoints
!bash download_ckpts_base.sh

/content/warehouse-activity-tracker/checkpoints
--2026-04-03 13:34:06--  https://dl.fbaipublicfiles.com/segment_anything_2/092824/sam2.1_hiera_base_plus.pt
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 13.249.182.33, 13.249.182.39, 13.249.182.81, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|13.249.182.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 323606802 (309M) [application/vnd.snesdev-page-table]
Saving to: ‘sam2.1_hiera_base_plus.pt.1’

sam2.1_hiera_base_p 100%[===================>] 308.62M   265MB/s    in 1.2s    

2026-04-03 13:34:07 (265 MB/s) - ‘sam2.1_hiera_base_plus.pt.1’ saved [323606802/323606802]

All checkpoints are downloaded successfully.


In [ ]:
# For GDINO checkpoints -- also custom ckpt
%cd /content/warehouse-activity-tracker/gdino_checkpoints
!bash download_ckpts_swint.sh

/content/warehouse-activity-tracker/gdino_checkpoints
--2026-04-03 13:34:07--  https://github.com/IDEA-Research/GroundingDINO/releases/download/v0.1.0-alpha/groundingdino_swint_ogc.pth
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/611591640/f221e500-c2fc-4fd3-b84e-8ad92a6923f3?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-04-03T14%3A15%3A58Z&rscd=attachment%3B+filename%3Dgroundingdino_swint_ogc.pth&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-04-03T13%3A15%3A45Z&ske=2026-04-03T14%3A15%3A58Z&sks=b&skv=2018-11-09&sig=rwG6iuZ%2FDI4MO9e6U6EnkxbTTrUR6uV5%2F5J8MAm0xwU%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2

# Testing of GDINO 1.0 Backbone on HuggingFace Model and Single Image

Will be runing the demo file, which contains video preprocessing like separating into several frames.

In [ ]:
# returning back to project root
%cd /content/warehouse-activity-tracker/

/content/warehouse-activity-tracker


In [ ]:

!python grounded_sam2_hf_model_demo.py \
  --img-path ./assets/tracking_car_1.jpg \
  --sam2-checkpoint ./checkpoints/sam2.1_hiera_base_plus.pt \
  --sam2-model-config configs/sam2.1/sam2.1_hiera_b+.yaml

preprocessor_config.json: 100% 457/457 [00:00<00:00, 2.10MB/s]
The image processor of type `GroundingDinoImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`. 
config.json: 1.64kB [00:00, 5.63MB/s]
tokenizer_config.json: 1.24kB [00:00, 3.73MB/s]
vocab.txt: 232kB [00:00, 14.6MB/s]
tokenizer.json: 711kB [00:00, 69.2MB/s]
added_tokens.json: 100% 82.0/82.0 [00:00<00:00, 499kB/s]
special_tokens_map.json: 100% 125/125 [00:00<00:00, 868kB/s]
model.safetensors: 100% 689M/689M [00:03<00:00, 179MB/s]
Loading weights: 100% 990/990 [00:01<00:00, 637.14it/s, Materializing param=model.text_projection.weight]


# Testing of GDINO 1.0 Backbone on HuggingFace Model and A Video

For this, I need to use this script directly: `grounded_sam2_tracking_demo_custom_video_input_gd1.0_hf_model.py`.

Note that I have modified it locally, so make sure to adjust the path when needed.

Don't forget to edit the model if necessary.

Remember the start frame formulation when stride is applied (current stride set to 3):

```
original_frame_idx = start + extracted_idx * stride
original_frame_idx = 0 + <what initial frame> * 3
```

In [ ]:
!python grounded_sam2_hf.py \
    --video-path /content/drive/MyDrive/warehouse_videos/safe_trolley.mp4 \
    --text-prompt "person. cart. pallet. trolley. pallet jack. jack." \
    --frame-start 120

The image processor of type `GroundingDinoImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`. 
Loading weights: 100% 990/990 [00:01<00:00, 673.11it/s, Materializing param=model.text_projection.weight]
VideoInfo(width=1280, height=720, fps=50, total_frames=648)
Saving Video Frames with Higher Stride and Lower Res: 176it [00:04, 38.99it/s]
frame loading (JPEG): 100% 176/176 [00:04<00:00, 35.90it/s]
[[404.5664   49.75633 476.54852 196.2072 ]
 [311.38855 142.2615  401.67465 314.11154]
 [ 76.3361  145.91023 245.01099 276.10995]]
['person', 'person', 'pallet pallet jack']

Skipping the post-processing step due to the error above. You can still use SAM 2 and it's OK to ignore the error above, although some post-processing functionality may be limited (which doesn't affec

In [ ]:
!python grounded_sam2_hf.py \
    --video-path /content/drive/MyDrive/warehouse_videos/unsafe_sandal.mp4 \
    --output-video-path ./unsafe_sandal_tracking_demo.mp4 \
    --text-prompt "person. sandal. pallet jack. pallet. stack. shorts." \
    --frame-start 120

The image processor of type `GroundingDinoImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`. 
Loading weights: 100% 990/990 [00:01<00:00, 675.80it/s, Materializing param=model.text_projection.weight]
VideoInfo(width=1280, height=720, fps=30, total_frames=1438)
Saving Video Frames with Higher Stride and Lower Res: 264it [00:05, 47.59it/s]
frame loading (JPEG): 100% 264/264 [00:08<00:00, 30.87it/s]
[[6.0910641e+01 1.8544257e-01 1.7423326e+02 1.7612404e+02]
 [1.1070697e+02 1.5083563e+02 1.7363953e+02 1.7589438e+02]
 [8.8216537e+01 1.4101285e+02 1.1155338e+02 1.6047229e+02]
 [3.9385767e+02 2.6169777e-01 6.3928699e+02 1.6974916e+02]
 [6.1826820e+01 3.6531687e-03 1.4079349e+02 6.5441475e+01]]
['person', 'sandal', 'sandal', 'stack', 'shorts']

Skipping the post-processi

In [ ]:
!python grounded_sam2_hf.py \
    --video-path /content/drive/MyDrive/warehouse_videos/activity.mp4 \
    --output-video-path ./activity_tracking_demo.mp4 \
    --text-prompt "vest. shoes. trousers. long pants. pallet. pallet jack. forklift." \
    --frame-start 120

The image processor of type `GroundingDinoImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`. 
Loading weights: 100% 990/990 [00:01<00:00, 653.83it/s, Materializing param=model.text_projection.weight]
VideoInfo(width=1280, height=720, fps=29, total_frames=3200)
Saving Video Frames with Higher Stride and Lower Res: 257it [00:13, 19.22it/s]
frame loading (JPEG): 100% 257/257 [00:08<00:00, 29.41it/s]
[[378.1154   176.91605  428.2351   245.1126  ]
 [430.8191     8.839606 594.6801   358.51706 ]
 [384.98767  121.9923   428.8509   181.23956 ]]
['long pants', 'forklift', 'vest']

Skipping the post-processing step due to the error above. You can still use SAM 2 and it's OK to ignore the error above, although some post-processing functionality may be limited (which doesn't 

In [ ]:
!python grounded_sam2_hf.py \
    --video-path /content/drive/MyDrive/warehouse_videos/forklift.mp4 \
    --output-video-path ./forklift_tracking_demo.mp4 \
    --text-prompt "person. shoes. vest. jacket. forklift." \
    --frame-start 60

The image processor of type `GroundingDinoImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`. 
Loading weights: 100% 990/990 [00:01<00:00, 642.68it/s, Materializing param=model.text_projection.weight]
VideoInfo(width=1280, height=720, fps=50, total_frames=297)
Saving Video Frames with Higher Stride and Lower Res: 119it [00:01, 94.95it/s] 
frame loading (JPEG): 100% 119/119 [00:04<00:00, 25.61it/s]
[[177.82439    1.336416 544.874    359.21014 ]
 [546.63513  142.23743  639.593    265.27316 ]
 [447.3296    77.46202  567.1893   171.59341 ]
 [607.77734   50.334602 639.8672   146.0622  ]
 [547.1264   248.43488  582.9358   264.69406 ]]
['forklift', 'person', 'person', 'person', 'shoes']

Skipping the post-processing step due to the error above. You can still use SAM 2 an