# Clone Repo

In [ ]:
# Clone cleaned up repo
!git clone https://github.com/javaliKai/warehouse-activity-tracker.git

Cloning into 'warehouse-activity-tracker'...
remote: Enumerating objects: 1530, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 1530 (delta 20), reused 28 (delta 9), pack-reused 1488 (from 1)
Receiving objects: 100% (1530/1530), 158.01 MiB | 43.42 MiB/s, done.
Resolving deltas: 100% (487/487), done.


# Install Deps

In [ ]:
# verify pytorch installation
import torch
print("Torch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA version:", torch.version.cuda)

Torch: 2.10.0+cu128
CUDA available: True
CUDA version: 12.8


In [ ]:
# set cuda home
import os
os.environ["CUDA_HOME"] = "/usr/local/cuda"  # this is the default google colab location of cuda
print(os.environ["CUDA_HOME"])

/usr/local/cuda


In [ ]:
# install SAM2
!cd warehouse-activity-tracker && pip install -e .

Obtaining file:///content/warehouse-activity-tracker
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 3.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.5/154.5 kB 10.0 MB/s eta 0:00:00
  Building editable for SAM-2 (pyproject.toml) ... done
  Created wheel for SAM-2: filename=sam_2-1.0-0.editable-cp312-cp312-linux_x86_64.whl size=24134 sha256=cb278a7709c674ff82a523f190794966099b31b7621cfe0bf63dbae4ed1b2d2e
  Stored in directory: /tmp/pip-ephem-wheel-cache-p7rsxhqq/wheels/2f/6a/01/1151ac797fd33b5746405ed3fb3e55062c7f5abaa4f0a021a4
  Created wheel for iopath: filename=iopath-0.1.10-py3-none-any.whl size=31527 sha256=1bcc3fe04a5477afef36bfcf548ab0c3fbbe3eed2b7aadf77ac928e8889f4e21
  Stored in directory: /root/.cache

In [ ]:
# install grounding dino
!cd warehouse-activity-tracker/ && pip install --no-build-isolation -e grounding_dino

Obtaining file:///content/warehouse-activity-tracker/grounding_dino
  Preparing metadata (setup.py) ... done
  Running setup.py develop for groundingdino


In [ ]:
# install extra deps that are not listed in the setup.py
!pip install supervision addict yapf

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.8/46.8 kB 3.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.9/41.9 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 217.4/217.4 kB 14.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 256.2/256.2 kB 26.9 MB/s eta 0:00:00


# Download Checkpoints

In [ ]:
# For SAM2 checkpoints -- currently using custom to directly get base ckpt
%cd /content/warehouse-activity-tracker/checkpoints
!bash download_ckpts_base.sh

/content/warehouse-activity-tracker/checkpoints
--2026-04-06 13:15:31--  https://dl.fbaipublicfiles.com/segment_anything_2/092824/sam2.1_hiera_base_plus.pt
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 3.165.160.70, 3.165.160.120, 3.165.160.106, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|3.165.160.70|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 323606802 (309M) [application/vnd.snesdev-page-table]
Saving to: ‘sam2.1_hiera_base_plus.pt’

sam2.1_hiera_base_p 100%[===================>] 308.62M  45.2MB/s    in 7.1s    

2026-04-06 13:15:39 (43.7 MB/s) - ‘sam2.1_hiera_base_plus.pt’ saved [323606802/323606802]

All checkpoints are downloaded successfully.


In [ ]:
# For GDINO checkpoints -- also custom ckpt
%cd /content/warehouse-activity-tracker/gdino_checkpoints
!bash download_ckpts_swint.sh

/content/warehouse-activity-tracker/gdino_checkpoints
--2026-04-06 13:15:39--  https://github.com/IDEA-Research/GroundingDINO/releases/download/v0.1.0-alpha/groundingdino_swint_ogc.pth
Resolving github.com (github.com)... 140.82.116.4
Connecting to github.com (github.com)|140.82.116.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/611591640/f221e500-c2fc-4fd3-b84e-8ad92a6923f3?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-04-06T14%3A08%3A43Z&rscd=attachment%3B+filename%3Dgroundingdino_swint_ogc.pth&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-04-06T13%3A07%3A50Z&ske=2026-04-06T14%3A08%3A43Z&sks=b&skv=2018-11-09&sig=82QeK8prKhTLDUwPP9tioJRTGhaR5goNf6d59vGIQsI%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MS

# Testing of GDINO 1.0 Backbone on HuggingFace Model and Single Image

Will be runing the demo file, which contains video preprocessing like separating into several frames.

In [ ]:
# returning back to project root
%cd /content/warehouse-activity-tracker/

/content/warehouse-activity-tracker


# Testing of GDINO 1.0 Backbone on HuggingFace Model and A Video

For this, I need to use this script directly: `grounded_sam2_tracking_demo_custom_video_input_gd1.0_hf_model.py`.

Note that I have modified it locally, so make sure to adjust the path when needed.

Don't forget to edit the model if necessary.

Remember the start frame formulation when stride is applied (current stride set to 3):

```
original_frame_idx = start + extracted_idx * stride
original_frame_idx = 0 + <what initial frame> * 3
```

In [ ]:
!python grounded_sam2_hf_judge.py \
    --video-path /content/drive/MyDrive/warehouse_videos/unsafe_sandal.mp4 \
    --output-video-path ./unsafe_sandal_tracking_demo.mp4 \
    --text-prompt "person. sandal. pallet jack. pallet. stack. shorts." \
    --frame-start 120 \
    --frame-stride 8

The image processor of type `GroundingDinoImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`. 
Loading weights: 100% 990/990 [00:01<00:00, 679.25it/s, Materializing param=model.text_projection.weight]
VideoInfo(width=1280, height=720, fps=30, total_frames=1438)
Saving Video Frames with Higher Stride and Lower Res: 165it [00:05, 31.75it/s]
frame loading (JPEG): 100% 165/165 [00:05<00:00, 27.90it/s]
[[6.0910641e+01 1.8544257e-01 1.7423326e+02 1.7612404e+02]
 [1.1070697e+02 1.5083563e+02 1.7363953e+02 1.7589438e+02]
 [8.8216537e+01 1.4101285e+02 1.1155338e+02 1.6047229e+02]
 [3.9385767e+02 2.6169777e-01 6.3928699e+02 1.6974916e+02]
 [6.1826820e+01 3.6531687e-03 1.4079349e+02 6.5441475e+01]]
['person', 'sandal', 'sandal', 'stack', 'shorts']

Skipping the post-processi

In [ ]:
!python grounded_sam2_hf_judge.py \
    --video-path /content/drive/MyDrive/warehouse_videos/forklift.mp4 \
    --output-video-path ./forklift_tracking_demo.mp4 \
    --text-prompt "person. shoes. vest. jacket. forklift." \
    --frame-start 60 \
    --frame-stride 3

The image processor of type `GroundingDinoImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`. 
Loading weights: 100% 990/990 [00:01<00:00, 650.81it/s, Materializing param=model.text_projection.weight]
VideoInfo(width=1280, height=720, fps=50, total_frames=297)
Saving Video Frames with Higher Stride and Lower Res: 79it [00:01, 68.74it/s]
frame loading (JPEG): 100% 79/79 [00:02<00:00, 35.78it/s]
[[177.82439    1.336416 544.874    359.21014 ]
 [546.63513  142.23743  639.593    265.27316 ]
 [447.3296    77.46202  567.1893   171.59341 ]
 [607.77734   50.334602 639.8672   146.0622  ]
 [547.1264   248.43488  582.9358   264.69406 ]]
['forklift', 'person', 'person', 'person', 'shoes']

Skipping the post-processing step due to the error above. You can still use SAM 2 and it