# Clone Repo

In [ ]:
# Clone cleaned up repo
!git clone https://github.com/javaliKai/warehouse-activity-tracker.git

Cloning into 'warehouse-activity-tracker'...
remote: Enumerating objects: 1510, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 1510 (delta 8), reused 15 (delta 3), pack-reused 1488 (from 1)
Receiving objects: 100% (1510/1510), 158.00 MiB | 13.23 MiB/s, done.
Resolving deltas: 100% (475/475), done.


# Install Deps

In [ ]:
# verify pytorch installation
import torch
print("Torch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA version:", torch.version.cuda)

Torch: 2.10.0+cu128
CUDA available: True
CUDA version: 12.8


In [ ]:
# set cuda home
import os
os.environ["CUDA_HOME"] = "/usr/local/cuda"  # this is the default google colab location of cuda
print(os.environ["CUDA_HOME"])

/usr/local/cuda


In [ ]:
# install SAM2
!cd warehouse-activity-tracker && pip install -e .

Obtaining file:///content/warehouse-activity-tracker
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 4.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.5/154.5 kB 13.9 MB/s eta 0:00:00
  Building editable for SAM-2 (pyproject.toml) ... done
  Created wheel for SAM-2: filename=sam_2-1.0-0.editable-cp312-cp312-linux_x86_64.whl size=24134 sha256=b7dace0921f7f51c31c14be21a26786039ae99079013421136d84c43c056cae7
  Stored in directory: /tmp/pip-ephem-wheel-cache-_7u29vus/wheels/2f/6a/01/1151ac797fd33b5746405ed3fb3e55062c7f5abaa4f0a021a4
  Created wheel for iopath: filename=iopath-0.1.10-py3-none-any.whl size=31527 sha256=269f58271b62416e023ec7304538f0e5696e059d3bba11e4d9191e99d884cd82
  Stored in directory: /root/.cache

In [ ]:
# install grounding dino
!cd warehouse-activity-tracker/ && pip install --no-build-isolation -e grounding_dino

Obtaining file:///content/warehouse-activity-tracker/grounding_dino
  Preparing metadata (setup.py) ... done
  Running setup.py develop for groundingdino


In [ ]:
# install extra deps that are not listed in the setup.py
!pip install supervision addict yapf

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.8/46.8 kB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.9/41.9 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 217.4/217.4 kB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 256.2/256.2 kB 13.6 MB/s eta 0:00:00


# Download Checkpoints

In [ ]:
# For SAM2 checkpoints -- currently using custom to directly get base ckpt
%cd /content/warehouse-activity-tracker/checkpoints
!bash download_ckpts_base.sh

/content/warehouse-activity-tracker/checkpoints
--2026-04-02 13:13:35--  https://dl.fbaipublicfiles.com/segment_anything_2/092824/sam2.1_hiera_base_plus.pt
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 13.35.37.90, 13.35.37.123, 13.35.37.84, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|13.35.37.90|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 323606802 (309M) [application/vnd.snesdev-page-table]
Saving to: ‘sam2.1_hiera_base_plus.pt’

sam2.1_hiera_base_p 100%[===================>] 308.62M   272MB/s    in 1.1s    

2026-04-02 13:13:37 (272 MB/s) - ‘sam2.1_hiera_base_plus.pt’ saved [323606802/323606802]

All checkpoints are downloaded successfully.


In [ ]:
# For GDINO checkpoints -- also custom ckpt
%cd /content/warehouse-activity-tracker/gdino_checkpoints
!bash download_ckpts_swint.sh

/content/warehouse-activity-tracker/gdino_checkpoints
--2026-04-02 13:13:37--  https://github.com/IDEA-Research/GroundingDINO/releases/download/v0.1.0-alpha/groundingdino_swint_ogc.pth
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/611591640/f221e500-c2fc-4fd3-b84e-8ad92a6923f3?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-04-02T13%3A56%3A33Z&rscd=attachment%3B+filename%3Dgroundingdino_swint_ogc.pth&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-04-02T12%3A55%3A47Z&ske=2026-04-02T13%3A56%3A33Z&sks=b&skv=2018-11-09&sig=0ynvPbHbMyKRCghva7Bc5TVvSqKiktOPVB8CndhNr6w%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2

# Testing of GDINO 1.0 Backbone on HuggingFace Model and Single Image

Will be runing the demo file, which contains video preprocessing like separating into several frames.

In [ ]:
# returning back to project root
%cd /content/warehouse-activity-tracker/

/content/warehouse-activity-tracker


In [ ]:
!python isolated_dino.py \
  --video-path /content/drive/MyDrive/warehouse_videos/unsafe_sandal.mp4 \
  --text-prompt "person. flipper. sandal. pallet jack. pallet. stack." \
  --frame-start 100

The image processor of type `GroundingDinoImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`. 
Loading weights: 100% 990/990 [00:01<00:00, 650.60it/s, Materializing param=model.text_projection.weight]
VideoInfo(width=1280, height=720, fps=30, total_frames=1438)
Saving Video Frames with Higher Stride and Lower Res: 446it [00:06, 73.26it/s]
[[5.5379642e+01 1.6498804e-01 1.8016586e+02 1.8936322e+02]
 [1.1546060e+02 1.6228134e+02 1.7994553e+02 1.8911125e+02]
 [4.0503790e+02 3.2415032e-01 6.3913000e+02 1.8575452e+02]
 [9.0667068e+01 1.5155035e+02 1.1549931e+02 1.7279980e+02]]
[0.8175744414329529, 0.5846269130706787, 0.5688949227333069, 0.47353553771972656]
['person', 'sandal', 'stack', 'sandal']


In [ ]:
!python isolated_dino.py \
  --video-path /content/drive/MyDrive/warehouse_videos/safe_trolley.mp4 \
  --text-prompt "person. cart. pallet. trolley. pallet jack. jack." \
  --frame-start 120

The image processor of type `GroundingDinoImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`. 
Loading weights: 100% 990/990 [00:01<00:00, 671.60it/s, Materializing param=model.text_projection.weight]
VideoInfo(width=1280, height=720, fps=50, total_frames=648)
Saving Video Frames with Higher Stride and Lower Res: 176it [00:02, 68.41it/s]
[[404.5664   49.75633 476.54852 196.2072 ]
 [311.38855 142.2615  401.67465 314.11154]
 [ 76.3361  145.91023 245.01099 276.10995]]
[0.8529354333877563, 0.8652240633964539, 0.4263215959072113]
['person', 'person', 'pallet pallet jack']
